### ISSUE TITLE
Build for Linux

### ISSUE THREAD

**Issue by zeronoises** [david-c14/submarine-prototype-vcv#1]
[SubmarinePrototype-0.6.0-lin.zip](https://github.com/david-c14/submarine-prototype-vcv/files/1860224/SubmarinePrototype-0.6.0-lin.zip)

**Comment by david-c14** [comment]
Why thank you. That's very kind.

Actually Linux is the one platform that I can build for.  I just haven't got round to it. I'll have to sort out my manifest and do this properly.

Thanks again.
